services:
  backend:
    build: 
      context: ./backend
    container_name: alexisevt_backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      # El VPS expone el 8011, el contenedor escucha en el 8000
      - "127.0.0.1:8011:8000"
    volumes:
      - /home/iweb/alexisevt/data/images:/app/data/images

  frontend:
    build: 
      context: ./frontend
    container_name: alexisevt_frontend
    restart: always
    env_file:
      - ./frontend/.env
    ports:
      # El VPS expone el 3011, el contenedor escucha en el 3000
      - "127.0.0.1:3011:3000"
    depends_on:
      - backend
